// Builds index.html: one self-contained page (CSS + JS inlined) that runs by
// double-clicking, with no server and no network. Sources live in src/.
//
// Run: npm run build

import { readFileSync, writeFileSync } from 'node:fs'

const read = (p) => readFileSync(new URL(`../${p}`, import.meta.url), 'utf8')

// Turn the three ES modules into one classic script: drop imports, drop `export`.
const strip = (src) =>
  src
    .split('\n')
    .filter((l) => !/^\s*import\s.+from\s+['"].+['"]\s*;?\s*$/.test(l))
    .join('\n')
    .replace(/^(\s*)export\s+(const|function|class)\s/gm, '$1$2 ')

const js = ['src/data.js', 'src/engine.js', 'src/playground.js'].map((p) => `// ---- ${p} ----\n${strip(read(p))}`).join('\n\n')
const css = read('src/playground.css')

const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Embedding Loss Playground</title>
<meta name="description" content="Fine-tune a tiny embedding model in your browser with 7 sentence-transformers losses and watch what each one does.">
<!-- Generated by scripts/build.mjs from src/. Edit the sources, then run: npm run build -->
<style>
:root {
  --primary: 200 29% 45%;
  --foreground: 240 10% 3.9%;
  --muted-foreground: 240 3.8% 32%;
  --background: 0 0% 100%;
  --border: 240 5.9% 88%;
}
.dark {
  --primary: 195 95% 85%;
  --foreground: 0 0% 98%;
  --muted-foreground: 240 5% 74.9%;
  --background: 240 20.54% 5.2%;
  --border: 240 3.7% 22.9%;
  color-scheme: dark;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  background: hsl(var(--background));
  color: hsl(var(--foreground));
  font-family: system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
  line-height: 1.55;
}
.page { max-width: 58rem; margin: 0 auto; padding: 2rem 16px 3rem; }
.page h1 { font-size: 1.75rem; line-height: 1.2; margin: 0 0 0.5rem; letter-spacing: -0.01em; }
.page .lede { color: hsl(var(--muted-foreground)); margin: 0 0 1rem; max-width: 44rem; }
.page .links { display: flex; flex-wrap: wrap; gap: 0.5rem 1.25rem; font-size: 0.9rem; margin-bottom: 0.5rem; }
.page a { color: inherit; text-underline-offset: 3px; }
.page a:hover { color: hsl(var(--primary)); }
.page footer { margin-top: 2rem; font-size: 0.8rem; color: hsl(var(--muted-foreground)); }
.theme-toggle { font: inherit; font-size: 0.85rem; border: 1px solid hsl(var(--border)); background: transparent; color: inherit; border-radius: 999px; padding: 0.2rem 0.75rem; cursor: pointer; }
${css}
</style>
<script>
  (function () {
    var t = null
    try { t = localStorage.getItem('theme') } catch (e) {}
    var dark = t ? t === 'dark' : window.matchMedia('(prefers-color-scheme: dark)').matches
    document.documentElement.classList.toggle('dark', dark)
  })()
</script>
</head>
<body>
<main class="page">
  <h1>Embedding Loss Playground</h1>
  <p class="lede">Pick a dataset and a sentence-transformers loss, press <b>Train</b>, and watch a small embedding model fine-tune live in your browser. Every loss's forward pass and gradient is implemented exactly, so what you see is how that loss really behaves.</p>
  <div class="links">
    <a href="https://www.rutvikacharya.com/blog/embedding-loss-types">Read the blog post</a>
    <a href="https://github.com/datamokotow/embedding-loss-playground">Source on GitHub</a>
    <button class="theme-toggle" id="theme-toggle" type="button">Toggle dark mode</button>
  </div>
  <div id="playground"></div>
  <footer>A 32-dimensional bag-of-words model trained with Adam. Absolute numbers won't match a real transformer; the way each loss behaves does. MIT licensed.</footer>
</main>
<script>
(function () {
${js}

mountPlayground(document.getElementById('playground'))
document.getElementById('theme-toggle').addEventListener('click', function () {
  var dark = !document.documentElement.classList.contains('dark')
  document.documentElement.classList.toggle('dark', dark)
  try { localStorage.setItem('theme', dark ? 'dark' : 'light') } catch (e) {}
})
})()
</script>
</body>
</html>
`

writeFileSync(new URL('../index.html', import.meta.url), html)
console.log(`index.html written (${(html.length / 1024).toFixed(0)} KB)`)
